name: Build Sphinx PDF on PR

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk
        pip install sphinx

    - name: Check if documentation exists
      run: |
        if [ ! -d "documentation/" ]; then
          echo "Documentation directory does not exist."
          exit 0
        fi

    - name: Build PDF with Sphinx
      run: |
        cd documentation/
        make pdf
        
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: sphinx-pdf
        path: documentation/_build/latex/*.pdf

    - name: Git commit the pdf
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email ""
        git add documentation/_build/latex/*.pdf
        git commit -m "Update PDF"
        git push